- name: Users | Hermes | Create User
  user:
    name: hermes
    password_lock: yes
    system: yes

- name: Users | Hermes | Add Vault Key
  template:
    src: vault_key.j2
    dest: /home/hermes/.vault_key
    owner: hermes
    group: hermes
    mode: 0600

- name: Users | Hermes | Add Sudoers File
  copy:
    src: users/hermes/sudoers_hermes
    dest: /etc/sudoers.d/hermes
    owner: root
    group: root
    mode: 0440
