- name: Users | Luke | Create User
  tags: luke,sudo,users
  user:
    name: luke
    comment: "Luke Orth"
    password: "{{ luke_passwd | password_hash('sha512') }}"
    shell: /bin/zsh

- name: Users | Luke | Add Sudoers File
  tags: luke,settings,sudo,system,users
  copy:
    src: users/luke/sudoers_luke
    dest: /etc/sudoers.d/luke
    owner: root
    group: root
    mode: 0440

- name: Users | Luke | Create .ssh Directory
  tags: dotfiles,luke,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: luke
    group: luke
    mode: 0700
  with_items:
    - { dir: '/home/luke/.ssh' }

- name: Users | Luke | Add Public Key
  tags: dotfiles,luke,ssh,ssh-keys,users
  copy:
    src: users/luke/luke_id_ed25519.pub
    dest: /home/luke/.ssh/luke_id_ed25519.pub
    owner: luke
    group: luke
    mode: 0600

- name: Users | Luke | Add Private Key
  tags: dotfiles,luke,ssh,ssh-keys,users
  copy:
    src: users/luke/luke_id_ed25519
    dest: /home/luke/.ssh/luke_id_ed25519
    owner: luke
    group: luke
    mode: 0600

- name: Users | Luke | Create Fonts Directory
  tags: fonts,luke,users
  file:
    path: /home/luke/.local/share/fonts
    state: directory
    owner: luke
    group: luke
    mode: 0700

- name: Users | Luke | Create Dotfiles Directory
  tags: dotfiles,luke,users
  file:
    path: /home/luke/dotfiles
    state: directory
    owner: luke
    group: luke
    mode: 0700

- name: Users | Luke | Create Vim Undodir
  tags: dotfiles,luke,users
  file:
    path: /home/luke/.vim/.undodir
    state: directory
    owner: luke
    group: luke
    mode: 0700

- name: Users | Luke | Clone Dotfiles Repository
  tags: dotfiles,luke,users,git
  become: yes
  become_user: luke
  git:
    repo: git@github.com:LukeOrth/dotfiles.git
    dest: /home/luke/dotfiles
    accept_hostkey: yes
    key_file: /home/luke/.ssh/luke_id_ed25519
    force: yes

- name: Users | Luke | Replace Sensitive Environment Variables
  tags: dotfiles,scripts,luke,users
  lineinfile:
    path: /home/luke/dotfiles/zsh/.zshrc
    regexp: '^SENSITIVE_ENV_VARS'
    line: "{{ item }}"
  with_items:
    - {{ owm_api_key }}
    - {{ current_city }}

- name: Users | Luke | GNU Stow Symlink Dotfiles
  tags: dotfiles,luke,users
  shell: stow *
  args:
    chdir: /home/luke/dotfiles

- name: Users | Luke | Get Custom Weather Script
  tags: scripts,luke,users
  get_url:
    url: https://raw.githubusercontent.com/LukeOrth/scripts/master/weather.go
    dest: /usr/local/bin/
    mode: 0644

- name: Users | Luke | Build Weather Script
  tags: scripts,luke,users
  shell: go build weather.go
  args:
    chdir: /usr/local/bin

- name: Users | Luke | Make Weather Script Executable
  tags: scripts,luke,Users
  file:
    path: /usr/local/bin/weather
    owner: root
    group: root
    mode: 0755
