- name: Software | Fonts | Get Fonts From Repo
  tags: software,fonts
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
    dest: /home/luke/.local/share/fonts/
