# Load distribution-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Create the primary system/backup users
  - import_tasks: users/soteria.yml
  - import_tasks: users/root.yml
  - import_tasks: users/hermes.yml

  # Install utilities
  - import_tasks: software/packages_utilities.yml

  # Create my user
  - import_tasks: users/luke.yml

  # Set up the ansible environment
  - import_tasks: ansible_setup.yml

  # Install remaining software
  
  # Remove unwanted software
  - import_tasks: software/packages_cleanup.yml
  
  # Perform remaining tasks
  - import_tasks: system_setup/cron.yml
